apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: teaxr
  namespace: argocd
spec:
  # Project description
  description: Teaxr Project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - server: https://kubernetes.default.svc
    namespace: '*'

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  