apiVersion: v1
kind: Secret
metadata:
  name: route53-iam
  namespace: cert-manager #For ClusterIssuer, this needs to be cert-manager. For Issuer, this needs to be the same nm as the Issuer
type: Opaque
data:
  secretAccessKey: ENCODEDKEY

#sudo apt-get install apache2-utils
#echo -n "AWSACCESSKEY" | base64
# To decode: echo 'encodedString' | base64 --decode
