apiVersion: v1
kind: Secret
metadata:
  name: my-dockerkey
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ABCDEFG

# To get .dockerconfigjson:
# kubectl create secret docker-registry secret-temp --docker-server=docker-repo.gmetri.io --docker-username=username --docker-password=password
# kubectl get secret secret-temp -o yaml
# kubectl delete secret secret-temp
