apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - name: k8s-template
      insecureIgnoreHostKey: true
      url: git@github.com:sahil87/k8s-template
      sshPrivateKeySecret:
        name: argocd-secret
        key: privateKey
    - name: another-repo
      insecureIgnoreHostKey: true
      url: git@github.com:sahil87/another-repo
      sshPrivateKeySecret:
        name: argocd-secret
        key: privateKey
