apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: Opaque
data:
  #https://unix.stackexchange.com/questions/307994/compute-bcrypt-hash-from-command-line
  # htpasswd -bnB "" mypassword | tr -d ':'
  #echo -n 'aboveoutput' | base64
  admin.password: ABCDEFG

#SSH private key for git access:
#base64 of the bot user's private key. (`echo "key" | base64 -d` to decode)
  gmdevPrivateKey: ABCDEFGH
