apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/deployment.yaml
  - resources/ingress.yaml
  - resources/service.yaml

#Initialize the configmap, so that post this point, configmap merge configurations works seamlessly
configMapGenerator:
  - name: cm-z5api
    files:
      - env-saml/metadata.xml
    literals:
    - PUBLIC_REPO=z5api
