apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: dev
  cluster: cluster-name

namespace: ingress-nginx

resources:
  - https://github.com/kubernetes/ingress-nginx.git/deploy/static/provider/cloud?ref=controller-v1.0.0

patchesStrategicMerge:
  - overlays/cm.yaml
